// GENERATED by tools/asset-pipeline/scripts/og-cards.mjs — do not edit by hand.
// Regenerate with:  pnpm og:cards <productSlug>
//
// Keyed '<productSlug>/<colourSlug>', matching apps/viewer/public/og/<key>.jpg.
// Width and height are read back out of each written JPEG, so a card that is
// regenerated at a different size cannot leave a stale number here. Pinned by
// apps/viewer/worker/og-cards.test.ts, which fails if this file and the directory
// ever disagree in either direction.
export interface OgCard {
  width: number
  height: number
}

export const OG_CARDS: Record<string, OgCard> = {
  'r-xmp/lavender': { width: 1200, height: 1500 },
  'r-xmp/mint': { width: 1200, height: 1500 },
  'r-xmp/olive': { width: 1200, height: 1500 },
  'r-xmp/white': { width: 1200, height: 1500 },
  'r-xmp/wine': { width: 1200, height: 1500 },
  'rxps/black': { width: 1200, height: 1500 },
  'rxps/blush': { width: 1200, height: 1500 },
  'rxps/butter': { width: 1200, height: 1500 },
  'rxps/lime': { width: 1200, height: 1500 },
  'rxps/wine': { width: 1200, height: 1500 },
}
