// GENERATED by tools/asset-pipeline/scripts/og-cards.mjs — do not edit by hand.
// Regenerate with:  pnpm og:cards <productSlug>
//
// Keyed '<productSlug>/<colourSlug>', matching apps/viewer/public/og/<key>.jpg.
// Width and height are read back out of each written JPEG, so a card that is
// regenerated at a different size cannot leave a stale number here. Pinned by
// apps/viewer/worker/og-cards.test.ts, which fails if this file and the directory
// ever disagree in either direction.
export interface OgCard {
  width: number
  height: number
}

export const OG_CARDS: Record<string, OgCard> = {
  'r-afp/butter': { width: 1200, height: 1500 },
  'r-afp/mauve': { width: 1200, height: 1500 },
  'r-afp/mustard': { width: 1200, height: 1500 },
  'r-afp/petrol': { width: 1200, height: 1500 },
  'r-afp/sky': { width: 1200, height: 1500 },
  'r-aj/indigo': { width: 1200, height: 1500 },
  'r-aj/lime': { width: 1200, height: 1500 },
  'r-aj/magenta': { width: 1200, height: 1500 },
  'r-aj/pebble': { width: 1200, height: 1500 },
  'r-aj/tangerine': { width: 1200, height: 1500 },
  'r-ajm/beige': { width: 1200, height: 1500 },
  'r-ajm/bottle-green': { width: 1200, height: 1500 },
  'r-ajm/coral': { width: 1200, height: 1500 },
  'r-ajm/powder-blue': { width: 1200, height: 1500 },
  'r-ajm/terracotta': { width: 1200, height: 1500 },
  'r-asb/blush': { width: 1200, height: 1500 },
  'r-asb/burgundy': { width: 1200, height: 1500 },
  'r-asb/pebble': { width: 1200, height: 1500 },
  'r-asb/petrol': { width: 1200, height: 1500 },
  'r-asb/sage': { width: 1200, height: 1500 },
  'r-atj/ash': { width: 1200, height: 1500 },
  'r-atj/burgundy': { width: 1200, height: 1500 },
  'r-atj/navy': { width: 1200, height: 1500 },
  'r-atj/powder-blue': { width: 1200, height: 1500 },
  'r-atj/sage': { width: 1200, height: 1500 },
  'r-atw/bone': { width: 1200, height: 1500 },
  'r-atw/citron': { width: 1200, height: 1500 },
  'r-atw/fuchsia': { width: 1200, height: 1500 },
  'r-atw/sage': { width: 1200, height: 1500 },
  'r-atw/turquoise': { width: 1200, height: 1500 },
  'r-css/blush': { width: 1200, height: 1500 },
  'r-css/lilac': { width: 1200, height: 1500 },
  'r-css/peach': { width: 1200, height: 1500 },
  'r-css/sky': { width: 1200, height: 1500 },
  'r-css/slate': { width: 1200, height: 1500 },
  'r-mm/ash': { width: 1200, height: 1500 },
  'r-mm/blush': { width: 1200, height: 1500 },
  'r-mm/lilac': { width: 1200, height: 1500 },
  'r-mm/sage': { width: 1200, height: 1500 },
  'r-mm/sky': { width: 1200, height: 1500 },
  'r-wzu/beige': { width: 1200, height: 1500 },
  'r-wzu/blush': { width: 1200, height: 1500 },
  'r-wzu/butter': { width: 1200, height: 1500 },
  'r-wzu/plum': { width: 1200, height: 1500 },
  'r-wzu/powder-blue': { width: 1200, height: 1500 },
  'r-xmp/lavender': { width: 1200, height: 1500 },
  'r-xmp/mint': { width: 1200, height: 1500 },
  'r-xmp/olive': { width: 1200, height: 1500 },
  'r-xmp/white': { width: 1200, height: 1500 },
  'r-xmp/wine': { width: 1200, height: 1500 },
  'rxps/black': { width: 1200, height: 1500 },
  'rxps/blush': { width: 1200, height: 1500 },
  'rxps/butter': { width: 1200, height: 1500 },
  'rxps/lime': { width: 1200, height: 1500 },
  'rxps/wine': { width: 1200, height: 1500 },
}
