/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    colourways: Colourway;
    events: Event;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    colourways: ColourwaysSelect<false> | ColourwaysSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admin / Director: full control including users and configuration. Editor: manages products, colourways and media only.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Optimised, pipeline-processed GLB models and poster images only. Run every product GLB through the asset pipeline (merge + validate) before uploading — never upload raw CLO exports. Posters: WebP/AVIF preferred. Keep files under 8 MB where possible.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive alternative text, e.g. "Velocity Performance Tee in Navy, front three-quarter view".
   */
  alt: string;
  /**
   * ADMIN ONLY — internal pointer to the CLO source (.zprj) location. Never exposed publicly and never uploaded here.
   */
  sourceReference?: string | null;
  /**
   * Automatically ticked when the file exceeds the 8 MB mobile guideline.
   */
  sizeWarning?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Unique uppercase code, e.g. N001.
   */
  productCode: string;
  /**
   * URL segment: viewer.wear-run.help/<slug>/<colour>.
   */
  slug: string;
  /**
   * Buyer-friendly name, e.g. Velocity Performance Tee.
   */
  productName: string;
  category: 'Sportswear' | 'Teamwear & Uniforms' | 'Casual Wear' | 'Outerwear' | 'Sports Accessories';
  status: 'draft' | 'published' | 'archived';
  /**
   * Use "separate GLB per colourway" whenever the merged multi-variant GLB fails, looks wrong, or is not processed yet — publishing must never be blocked.
   */
  variantMode: 'single-glb-variants' | 'separate-glb-per-colour';
  /**
   * Manually verified that the merged GLB’s availableVariants exactly matches the colourway variantIds (asset pipeline "validate" + scenegraph check). Required to publish.
   */
  variantsVerified?: boolean | null;
  /**
   * The active colourway shown when a QR link’s colourway is retired or missing.
   */
  defaultColourway?: (number | null) | Colourway;
  presentationMode: 'floatingGarment' | 'invisibleMannequin';
  /**
   * The merged production GLB from the asset pipeline (all colourways bound as KHR_materials_variants). Never a raw CLO export.
   */
  glbAsset?: (number | null) | Media;
  /**
   * Static render shown instantly and used when 3D cannot load.
   */
  posterFallback?: (number | null) | Media;
  /**
   * e.g. Recycled polyester / elastane.
   */
  fabricComposition?: string | null;
  /**
   * e.g. 160 GSM.
   */
  gsm?: string | null;
  /**
   * Short technical phrases, e.g. "Moisture management".
   */
  performanceFeatures?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. Athletic regular.
   */
  garmentFit?: string | null;
  /**
   * Shown in the customisation section. B2B/OEM language only — no retail wording.
   */
  customisationIntro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The "How we build your product" steps.
   */
  customisationSteps?:
    | {
        number: number;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  frontCameraOrbit: string;
  backCameraOrbit: string;
  sideCameraOrbit: string;
  cameraTarget: string;
  defaultFieldOfView: string;
  catalogueUrl: string;
  sortOrder?: number | null;
  /**
   * Shown when a scanned QR points at a colourway that is no longer active.
   */
  retiredMessage: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colourways".
 */
export interface Colourway {
  id: number;
  product: number | Product;
  /**
   * Structured ID, e.g. N001-NAVY. Must exactly match the KHR_materials_variants name inside the merged GLB (single-GLB mode).
   */
  variantId: string;
  /**
   * e.g. Navy.
   */
  displayName: string;
  /**
   * URL segment: viewer.wear-run.help/<product>/<slug>. Printed in QR codes — never change it once QRs are in the field; retire the colourway instead.
   */
  slug: string;
  /**
   * Tab order: 01, 02, 03…
   */
  sequence: number;
  /**
   * Static CLO front three-quarter render. Shows instantly while 3D loads.
   */
  posterPreview: number | Media;
  /**
   * This colourway’s own GLB — used only when the parent product’s variant mode is "separate GLB per colourway". Still must be pipeline-validated.
   */
  glbAsset?: (number | null) | Media;
  /**
   * Inactive colourways disappear from the viewer; QR links to them fall back to the default colourway.
   */
  active?: boolean | null;
  /**
   * Exactly one active colourway per product. Marking this un-marks the others.
   */
  isDefault?: boolean | null;
  /**
   * Accessible description, e.g. "Velocity Performance Tee in Navy".
   */
  altText: string;
  /**
   * Admin recognition only — never the sole visual selector on the viewer.
   */
  hexSwatch?: string | null;
  /**
   * Internal note (never shown publicly).
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Anonymous viewer analytics, diagnostics and client errors. No IP or personal data is stored. Written only by the public events endpoint; prune periodically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  type: 'analytics' | 'diagnostic' | 'error';
  event: string;
  product?: string | null;
  variant?: string | null;
  placement?: string | null;
  /**
   * Client error message (errors only).
   */
  message?: string | null;
  /**
   * Coarse, truncated user-agent. No IP is stored.
   */
  ua?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'colourways';
        value: number | Colourway;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sourceReference?: T;
  sizeWarning?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  productCode?: T;
  slug?: T;
  productName?: T;
  category?: T;
  status?: T;
  variantMode?: T;
  variantsVerified?: T;
  defaultColourway?: T;
  presentationMode?: T;
  glbAsset?: T;
  posterFallback?: T;
  fabricComposition?: T;
  gsm?: T;
  performanceFeatures?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  garmentFit?: T;
  customisationIntro?: T;
  customisationSteps?:
    | T
    | {
        number?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  frontCameraOrbit?: T;
  backCameraOrbit?: T;
  sideCameraOrbit?: T;
  cameraTarget?: T;
  defaultFieldOfView?: T;
  catalogueUrl?: T;
  sortOrder?: T;
  retiredMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colourways_select".
 */
export interface ColourwaysSelect<T extends boolean = true> {
  product?: T;
  variantId?: T;
  displayName?: T;
  slug?: T;
  sequence?: T;
  posterPreview?: T;
  glbAsset?: T;
  active?: T;
  isDefault?: T;
  altText?: T;
  hexSwatch?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  type?: T;
  event?: T;
  product?: T;
  variant?: T;
  placement?: T;
  message?: T;
  ua?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  email: string;
  /**
   * International format; the viewer builds wa.me links from the digits.
   */
  whatsappNumber: string;
  catalogueUrl: string;
  temporaryWordmark: string;
  footerLine: string;
  legalLine: string;
  /**
   * Reference copy of the enquiry template the viewer generates for email/WhatsApp. Tokens: [Product Name], [Product Code], [Colour].
   */
  inquiryTemplate?: {
    subject?: string | null;
    bodyIntro?: string | null;
    microcopy?: string | null;
  };
  /**
   * Cloudflare Web Analytics only — cookieless, no third-party trackers.
   */
  analytics?: {
    /**
     * Cloudflare Web Analytics beacon token for the viewer site (optional).
     */
    cfBeaconToken?: string | null;
  };
  /**
   * Public viewer API behaviour.
   */
  viewerApi?: {
    /**
     * Edge cache lifetime for public viewer responses.
     */
    cacheSeconds?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  email?: T;
  whatsappNumber?: T;
  catalogueUrl?: T;
  temporaryWordmark?: T;
  footerLine?: T;
  legalLine?: T;
  inquiryTemplate?:
    | T
    | {
        subject?: T;
        bodyIntro?: T;
        microcopy?: T;
      };
  analytics?:
    | T
    | {
        cfBeaconToken?: T;
      };
  viewerApi?:
    | T
    | {
        cacheSeconds?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}