/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Every colour this garment comes in. Drag to reorder — the top colour that is switched on is the one people see when they open the page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductColourway".
 */
export type ProductColourway =
  | {
      /**
       * What buyers see on the colour button, e.g. Navy.
       */
      displayName: string;
      /**
       * The word in this colour’s link and QR code: wear-run.help/n001/navy. Lowercase, no spaces. Never change it once QR codes are printed — switch the colour off instead.
       */
      slug: string;
      /**
       * Upload your CLO file on the “3D file” tab first. Once it has been read, this list fills with the colours found inside it — pick the one that matches.
       */
      variantId?: string | null;
      /**
       * A picture of the garment in this colour. It appears instantly while the spinning 3D model loads.
       */
      posterPreview?: (number | null) | Media;
      /**
       * Describe the photo in a sentence, for people who use a screen reader. e.g. “Velocity Performance Tee in Navy”.
       */
      altText?: string | null;
      /**
       * A colour code like #22314E, only so you can recognise the row at a glance. Buyers never see it.
       */
      hexSwatch?: string | null;
      /**
       * Only needed because this product is set to “A separate file for each colour”. Leave empty otherwise.
       */
      glbAsset?: (number | null) | Media;
      /**
       * Untick to retire a colour. Old QR codes still work — they show your first colour instead, with the retired message.
       */
      active?: boolean | null;
      /**
       * Notes to yourself. Never shown to customers.
       */
      note?: string | null;
      id?: string | null;
    }[]
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'raw-uploads': RawUpload;
    products: Product;
    events: Event;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    products: {
      rawUploads: 'raw-uploads';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'raw-uploads': RawUploadsSelect<false> | RawUploadsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admin / Director: full control including users and configuration. Editor: manages products, colourways and media only.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Every picture and finished 3D file used on the website. Shrunk 3D files arrive here on their own once your CLO upload has been processed — you rarely need to add anything by hand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive alternative text, e.g. "Velocity Performance Tee in Navy, front three-quarter view".
   */
  alt: string;
  /**
   * ADMIN ONLY — internal pointer to the CLO source (.zprj) location. Never exposed publicly and never uploaded here.
   */
  sourceReference?: string | null;
  /**
   * Automatically ticked when the file exceeds the 8 MB mobile guideline.
   */
  sizeWarning?: boolean | null;
  /**
   * Written by the shrink robot. “Damaged” means printed logos or lettering were torn while the file was made smaller, and the product will refuse to publish until the file is replaced.
   */
  artworkVerdict?: ('unknown' | 'ok' | 'damaged') | null;
  /**
   * Write why this file is acceptable despite the warning — e.g. “this garment has no printed artwork”. Any text here lets it publish, and it stays on the record.
   */
  artworkOverrideReason?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Upload your raw CLO export here — big files and messy names are fine (give it a name ending in “.glb” so the records stay readable). It is shrunk automatically. When Status shows “ready”, open the linked product to review the colours and Publish. These files are private and never shown to customers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "raw-uploads".
 */
export interface RawUpload {
  id: number;
  /**
   * Which product this garment is for. Required: the robot writes the colours it found inside your file onto this product, and without it the Colours tab stays empty and the product cannot be published.
   */
  targetProduct: number | Product;
  /**
   * How much detail to keep. Start with Balanced. Re-upload on “Highest quality” only if a printed graphic came back SMEARED or TORN — ragged edges, warped lettering. That is mesh damage, and Detail is the setting that fixes it. If a graphic is SEE-THROUGH, or sits in a pale box, Detail will NOT help: every level makes the same transparency decision. Report that instead. If it is rejected for being too big, the file needs re-exporting from CLO at a lower mesh density — there is no smaller setting here, because the one that existed shrank files by damaging the printed graphics.
   */
  detail?: ('balanced' | 'fidelity') | null;
  /**
   * Set automatically. “Ready to review” means the shrunk GLB is waiting below.
   */
  status?: ('queued' | 'processing' | 'ready' | 'failed') | null;
  /**
   * Tick this and press Save to run the shrinking again. You do NOT need to upload the file a second time — it is still stored. Change the Detail setting first if you want a different result.
   */
  retry?: boolean | null;
  /**
   * The shrunk, pipeline-processed GLB the robot produced. Attach this to the product.
   */
  resultGlb?: (number | null) | Media;
  /**
   * The pipeline report: final size, the colour variants found in the file, and any warnings. Read this before publishing.
   */
  report?: string | null;
  /**
   * Optional note to yourself, e.g. which CLO “Colorway” maps to which colourway ID (Colorway 2 = N001-NAVY). The viewer switches colours by the variant names inside the GLB.
   */
  variantMapping?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * One page per garment. Fill it top to bottom: the basics, then the colours, then upload your CLO file on the “3D file” tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Nothing is public until this says Published.
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * What buyers see at the top of the page, e.g. Velocity Performance Tee.
   */
  productName: string;
  /**
   * Your internal code. Capital letters and numbers, e.g. N001.
   */
  productCode: string;
  /**
   * The word in this product’s link and QR codes: wear-run.help/n001/navy. Never change it once QR codes are printed.
   */
  slug: string;
  /**
   * Pick the closest match. Used for grouping only.
   */
  category: 'Sportswear' | 'Teamwear & Uniforms' | 'Casual Wear' | 'Outerwear' | 'Sports Accessories';
  /**
   * “Floating garment” suits most items. “Invisible mannequin” holds the shape of structured pieces like jackets.
   */
  presentationMode: 'floatingGarment' | 'invisibleMannequin';
  colourways?: ProductColourway;
  /**
   * Upload your raw CLO export here. Watch the Status column: Queued → Processing → Ready to review. Then pick the finished file below.
   */
  rawUploads?: {
    docs?: (number | RawUpload)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * “One file with all colours” is normal. Only switch to a separate file per colour if the combined file looks wrong — publishing must never be blocked.
   */
  variantMode: 'single-glb-variants' | 'separate-glb-per-colour';
  /**
   * The shrunk file the robot produced. Pick it from “Your CLO files” above once its Status says Ready to review. Never a raw CLO export.
   */
  glbAsset?: (number | null) | Media;
  /**
   * Shown if the 3D model cannot load on someone’s phone. Optional but recommended.
   */
  posterFallback?: (number | null) | Media;
  /**
   * Ticks itself once every colour on show has been matched to a colour inside your file. You do not set this.
   */
  variantsVerified?: boolean | null;
  /**
   * Set automatically when your CLO file is processed.
   */
  fileColours?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Set automatically when your CLO file is processed.
   */
  fileColourDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * e.g. Recycled polyester / elastane.
   */
  fabricComposition?: string | null;
  /**
   * e.g. 160 GSM.
   */
  gsm?: string | null;
  /**
   * e.g. Athletic regular.
   */
  garmentFit?: string | null;
  /**
   * Short phrases, e.g. “Moisture management”. One per row.
   */
  performanceFeatures?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The paragraph above the steps. Business-to-business wording only — this is not a shop.
   */
  customisationIntro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown in order as the “How we build your product” list.
   */
  customisationSteps?:
    | {
        number: number;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  frontCameraOrbit: string;
  backCameraOrbit: string;
  sideCameraOrbit: string;
  cameraTarget: string;
  defaultFieldOfView: string;
  /**
   * Where the “Catalogue” button sends people.
   */
  catalogueUrl: string;
  /**
   * Shown when someone scans a QR code for a colour that has been switched off.
   */
  retiredMessage: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Anonymous viewer analytics, diagnostics and client errors. No IP or personal data is stored. Written only by the public events endpoint; prune periodically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  type: 'analytics' | 'diagnostic' | 'error';
  event: string;
  product?: string | null;
  variant?: string | null;
  placement?: string | null;
  /**
   * Client error message (errors only).
   */
  message?: string | null;
  /**
   * Coarse, truncated user-agent. No IP is stored.
   */
  ua?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'raw-uploads';
        value: number | RawUpload;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sourceReference?: T;
  sizeWarning?: T;
  artworkVerdict?: T;
  artworkOverrideReason?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "raw-uploads_select".
 */
export interface RawUploadsSelect<T extends boolean = true> {
  targetProduct?: T;
  detail?: T;
  status?: T;
  retry?: T;
  resultGlb?: T;
  report?: T;
  variantMapping?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  status?: T;
  sortOrder?: T;
  productName?: T;
  productCode?: T;
  slug?: T;
  category?: T;
  presentationMode?: T;
  colourways?: T | ProductColourwaySelect<T>;
  rawUploads?: T;
  variantMode?: T;
  glbAsset?: T;
  posterFallback?: T;
  variantsVerified?: T;
  fileColours?: T;
  fileColourDetails?: T;
  fabricComposition?: T;
  gsm?: T;
  garmentFit?: T;
  performanceFeatures?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  customisationIntro?: T;
  customisationSteps?:
    | T
    | {
        number?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  frontCameraOrbit?: T;
  backCameraOrbit?: T;
  sideCameraOrbit?: T;
  cameraTarget?: T;
  defaultFieldOfView?: T;
  catalogueUrl?: T;
  retiredMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductColourway_select".
 */
export interface ProductColourwaySelect<T extends boolean = true> {
  displayName?: T;
  slug?: T;
  variantId?: T;
  posterPreview?: T;
  altText?: T;
  hexSwatch?: T;
  glbAsset?: T;
  active?: T;
  note?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  type?: T;
  event?: T;
  product?: T;
  variant?: T;
  placement?: T;
  message?: T;
  ua?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  email: string;
  /**
   * International format; the viewer builds wa.me links from the digits.
   */
  whatsappNumber: string;
  catalogueUrl: string;
  temporaryWordmark: string;
  footerLine: string;
  legalLine: string;
  /**
   * Reference copy of the enquiry template the viewer generates for email/WhatsApp. Tokens: [Product Name], [Product Code], [Colour].
   */
  inquiryTemplate?: {
    subject?: string | null;
    bodyIntro?: string | null;
    microcopy?: string | null;
  };
  /**
   * Cloudflare Web Analytics only — cookieless, no third-party trackers.
   */
  analytics?: {
    /**
     * Cloudflare Web Analytics beacon token for the viewer site (optional).
     */
    cfBeaconToken?: string | null;
  };
  /**
   * Public viewer API behaviour.
   */
  viewerApi?: {
    /**
     * Edge cache lifetime for public viewer responses.
     */
    cacheSeconds?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  email?: T;
  whatsappNumber?: T;
  catalogueUrl?: T;
  temporaryWordmark?: T;
  footerLine?: T;
  legalLine?: T;
  inquiryTemplate?:
    | T
    | {
        subject?: T;
        bodyIntro?: T;
        microcopy?: T;
      };
  analytics?:
    | T
    | {
        cfBeaconToken?: T;
      };
  viewerApi?:
    | T
    | {
        cacheSeconds?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}