/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Every colour this garment comes in. Drag to reorder — the top colour that is switched on is the one people see when they open the page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductColourway".
 */
export type ProductColourway =
  | {
      /**
       * What buyers see on the colour button, e.g. Navy.
       */
      displayName?: string | null;
      /**
       * The word for this colour in its link and QR code, like “bottle-green” in wear-run.com/products/r-ajm/bottle-green. Lowercase, no spaces. Never change it once QR codes are printed — switch the colour off instead.
       */
      slug?: string | null;
      /**
       * Upload your CLO file on the “3D file” tab first. Once it has been read, this list fills with the colours found inside it — pick the one that matches.
       */
      variantId?: string | null;
      /**
       * A picture of the garment in this colour. It appears instantly while the spinning 3D model loads.
       */
      posterPreview?: (number | null) | Media;
      /**
       * A large, sharp picture of this colour from CLO. Buyers can open it full-screen from the “HD image” button. Leave empty and the button stays hidden.
       */
      renderImage?: (number | null) | Media;
      /**
       * A smaller copy of the HD render above, shown inside the 3D window. Its file name is the render’s with “-screen” added (e.g. r-gtd-ash-render-screen.webp). Leave empty and the page shows the HD render itself.
       */
      renderScreen?: (number | null) | Media;
      /**
       * Describe the photo in a sentence, for people who use a screen reader. e.g. “Velocity Performance Tee in Navy”.
       */
      altText?: string | null;
      /**
       * A colour code like #22314E. Buyers see it as this colour’s round swatch on the product cards and on the garment page.
       */
      hexSwatch?: string | null;
      /**
       * Only needed because this product is set to “A separate file for each colour”. Leave empty otherwise.
       */
      glbAsset?: (number | null) | Media;
      /**
       * Untick to retire a colour. Old QR codes still work — they show your first colour instead, with the retired message.
       */
      active?: boolean | null;
      /**
       * Notes to yourself. Never shown to customers.
       */
      note?: string | null;
      id?: string | null;
    }[]
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'raw-uploads': RawUpload;
    products: Product;
    events: Event;
    inquiries: Inquiry;
    'inquiry-files': InquiryFile;
    'job-applications': JobApplication;
    'application-files': ApplicationFile;
    authors: Author;
    'journal-posts': JournalPost;
    'case-studies': CaseStudy;
    'document-visits': DocumentVisit;
    'document-visit-salts': DocumentVisitSalt;
    'document-visit-emails': DocumentVisitEmail;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    products: {
      rawUploads: 'raw-uploads';
    };
    inquiries: {
      files: 'inquiry-files';
    };
    'job-applications': {
      files: 'application-files';
    };
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'raw-uploads': RawUploadsSelect<false> | RawUploadsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'inquiry-files': InquiryFilesSelect<false> | InquiryFilesSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    'application-files': ApplicationFilesSelect<false> | ApplicationFilesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'journal-posts': JournalPostsSelect<false> | JournalPostsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'document-visits': DocumentVisitsSelect<false> | DocumentVisitsSelect<true>;
    'document-visit-salts': DocumentVisitSaltsSelect<false> | DocumentVisitSaltsSelect<true>;
    'document-visit-emails': DocumentVisitEmailsSelect<false> | DocumentVisitEmailsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'catalogue-defaults': CatalogueDefault;
    'build-process': BuildProcess;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'catalogue-defaults': CatalogueDefaultsSelect<false> | CatalogueDefaultsSelect<true>;
    'build-process': BuildProcessSelect<false> | BuildProcessSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admin / Director: full control including users and configuration. Editor: manages products, colourways and media only.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  hasAPIKey?: boolean | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Every picture and finished 3D file used on the website. Shrunk 3D files arrive here on their own once your CLO upload has been processed — you rarely need to add anything by hand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive alternative text, e.g. "Velocity Performance Tee in Navy, front three-quarter view".
   */
  alt: string;
  /**
   * ADMIN ONLY — internal pointer to the CLO source (.zprj) location. Never exposed publicly and never uploaded here.
   */
  sourceReference?: string | null;
  /**
   * Automatically ticked when the file exceeds the 8 MB mobile guideline.
   */
  sizeWarning?: boolean | null;
  /**
   * Written by the shrink robot. “Damaged” means printed logos or lettering were torn while the file was made smaller, and the product will refuse to publish until the file is replaced.
   */
  artworkVerdict?: ('unknown' | 'ok' | 'damaged') | null;
  /**
   * Write why this file is acceptable despite the warning — e.g. “this garment has no printed artwork”. Any text here lets it publish, and it stays on the record.
   */
  artworkOverrideReason?: string | null;
  _objectKey?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload your raw CLO export here — big files and messy names are fine (give it a name ending in “.glb” so the records stay readable). It is shrunk automatically. When Status shows “ready”, open the linked product to review the colours and Publish. These files are private and never shown to customers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "raw-uploads".
 */
export interface RawUpload {
  id: number;
  /**
   * Which product this garment is for. Required: the robot writes the colours it found inside your file onto this product, and without it the Colours tab stays empty and the product cannot be published.
   */
  targetProduct: number | Product;
  /**
   * How much detail to keep. Start with Balanced — and note that a small file (under 50 MB from CLO) is put on Highest quality automatically, because on a file that size the extra quality costs only a few hundred kilobytes. You do not need to do anything for that to happen. Re-upload on “Highest quality” only if a printed graphic came back SMEARED or TORN — ragged edges, warped lettering. That is mesh damage, and Detail is the setting that fixes it. If a graphic is SEE-THROUGH, or sits in a pale box, Detail will NOT help: every level makes the same transparency decision. Report that instead. If it is rejected for being too big, the file needs re-exporting from CLO at a lower mesh density — there is no smaller setting here, because the one that existed shrank files by damaging the printed graphics.
   */
  detail?: ('balanced' | 'fidelity') | null;
  /**
   * Set automatically. “Ready to review” means the shrunk GLB is waiting below.
   */
  status?: ('queued' | 'processing' | 'ready' | 'failed') | null;
  /**
   * Tick this and press Save to run the shrinking again. You do NOT need to upload the file a second time — it is still stored. Change the Detail setting first if you want a different result.
   */
  retry?: boolean | null;
  /**
   * The shrunk, pipeline-processed GLB the robot produced. Attach this to the product.
   */
  resultGlb?: (number | null) | Media;
  /**
   * The pipeline report: final size, the colour variants found in the file, and any warnings. Read this before publishing.
   */
  report?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * One page per garment. Fill it top to bottom: the basics, then the colours, then upload your CLO file on the “3D file” tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Nothing is public until this says Published.
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * What buyers see at the top of the page, e.g. Velocity Performance Tee.
   */
  productName: string;
  /**
   * What kind of garment it is, in the words a buyer would search. For example: Women's Tennis Dress, Men's Cycling Bib Shorts. Used in the page title search engines show. On Teamwear it also picks the sport button the garment is listed under (Soccer, Cycling, Tennis…). Leave blank if unsure.
   */
  garmentType?: string | null;
  /**
   * A few sentences about this garment, shown under its name on the public page. Plain text — no links or formatting. There is no length limit, though the page reads best at three or four sentences. Leave it blank and the page uses the standard development-reference wording instead.
   */
  shortDescription?: string | null;
  /**
   * Your internal code. Letters, numbers and hyphens, e.g. N001 or RX-PS. Lowercase is fine — it is saved in capitals.
   */
  productCode: string;
  /**
   * The word for this product in its link and QR codes, like “r-ajm” in wear-run.com/products/r-ajm/bottle-green. Never change it once QR codes are printed.
   */
  slug: string;
  /**
   * Pick the closest match. Used for grouping only.
   */
  category: 'Sportswear' | 'Teamwear & Uniforms' | 'Casual Wear' | 'Outerwear' | 'Sports Accessories';
  colourways?: ProductColourway;
  /**
   * Tick this to put the garment online before its 3D file is ready. Every colour then needs a photo, and the page shows that photo with a “3D view coming soon” note. Untick it once the finished 3D file is picked below.
   */
  modelComingSoon?: boolean | null;
  /**
   * Upload your raw CLO export here. Watch the Status column: Queued → Processing → Ready to review. Then pick the finished file below.
   */
  rawUploads?: {
    docs?: (number | RawUpload)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * “One file with all colours” is normal. Only switch to a separate file per colour if the combined file looks wrong — publishing must never be blocked.
   */
  variantMode: 'single-glb-variants' | 'separate-glb-per-colour';
  /**
   * The shrunk file the robot produced. Pick it from “Your CLO files” above once its Status says Ready to review. Never a raw CLO export.
   */
  glbAsset?: (number | null) | Media;
  /**
   * Shown if the 3D model cannot load on someone’s phone. Optional but recommended.
   */
  posterFallback?: (number | null) | Media;
  /**
   * Ticks itself once every colour on show has been matched to a colour inside your file. You do not set this.
   */
  variantsVerified?: boolean | null;
  /**
   * Set automatically when your CLO file is processed.
   */
  fileColours?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Set automatically when your CLO file is processed.
   */
  fileColourDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * e.g. Recycled polyester / elastane.
   */
  fabricComposition?: string | null;
  /**
   * e.g. 160 GSM.
   */
  gsm?: string | null;
  /**
   * e.g. Athletic regular.
   */
  garmentFit?: string | null;
  /**
   * Short phrases, e.g. “Moisture management”. One per row.
   */
  performanceFeatures?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * One short paragraph introducing how this garment is made. If you leave it blank the page shows a general sentence instead.
   */
  customisationIntro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Four steps is the shape every live garment uses. Fewer or more will render; none hides the section.
   */
  customisationSteps?:
    | {
        number: number;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  frontCameraOrbit: string;
  backCameraOrbit: string;
  sideCameraOrbit: string;
  cameraTarget: string;
  defaultFieldOfView: string;
  /**
   * Kept on record only. The website has had no “Catalogue” button since 4 September 2026 — these product pages are indexed by Google and the catalogue is a 54 MB trade PDF. Changing this does not change anything a visitor sees.
   */
  catalogueUrl: string;
  /**
   * Shown when someone scans a QR code for a colour that has been switched off.
   */
  retiredMessage: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Anonymous viewer analytics, diagnostics and client errors. No IP or personal data is stored. Written only by the public events endpoint; prune periodically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  type: 'analytics' | 'diagnostic' | 'error';
  event: string;
  product?: string | null;
  variant?: string | null;
  placement?: string | null;
  /**
   * Client error message (errors only).
   */
  message?: string | null;
  /**
   * Coarse, truncated user-agent. No IP is stored.
   */
  ua?: string | null;
  /**
   * Page speed (web vitals only): milliseconds until the largest element painted.
   */
  lcpMs?: number | null;
  /**
   * Page steadiness (web vitals only): the layout-shift score for the visit.
   */
  cls?: number | null;
  /**
   * Page response (web vitals only): milliseconds the slowest tap, click or key press of the visit took to show on screen.
   */
  inpMs?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages sent through the form on the contact page. Every one is saved here BEFORE the notification email is attempted, so a mail problem can never lose an inquiry — if the email did not arrive, the message is still on this screen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  company?: string | null;
  email: string;
  message: string;
  jobTitle?: string | null;
  country?: string | null;
  /**
   * Stored as typed, with the country code first.
   */
  phone?: string | null;
  subject?: string | null;
  /**
   * Files attached to this inquiry. They download when opened.
   */
  files?: {
    docs?: (number | InquiryFile)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Why an attached file could not be saved, if one could not. The message itself was saved.
   */
  filesError?: string | null;
  /**
   * The one field on this screen you are meant to change.
   */
  status: 'new' | 'replied' | 'archived';
  /**
   * Whether the notification email was accepted for delivery.
   */
  notified?: boolean | null;
  /**
   * Why the notification could not be sent, if it could not. The inquiry itself is unaffected — it is the message above.
   */
  notifyError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Files buyers attached to the contact form. Each belongs to one inquiry and is deleted with it. They download to your computer rather than opening here, because anyone can send one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiry-files".
 */
export interface InquiryFile {
  id: number;
  inquiry?: (number | null) | Inquiry;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Applications sent through the form on the careers page. Each is saved here BEFORE the notification email is attempted. Keep each one for 12 months, then delete it: the "Delete after" column shows the date.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: number;
  name: string;
  /**
   * Stored as typed, with the country code first.
   */
  phone: string;
  email?: string | null;
  /**
   * What they do: one of the form’s roles, or their own words.
   */
  role: string;
  years?: number | null;
  note?: string | null;
  /**
   * The CV, if one was sent. It downloads when opened.
   */
  files?: {
    docs?: (number | ApplicationFile)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Why a CV could not be saved, if one could not. The application itself was saved.
   */
  filesError?: string | null;
  /**
   * The one field on this screen you are meant to change.
   */
  status: 'new' | 'reviewed' | 'contacted';
  /**
   * 12 months after it arrived. Delete the application on or after this date.
   */
  deleteAfter?: string | null;
  /**
   * Whether the notification email was accepted for delivery.
   */
  notified?: boolean | null;
  /**
   * Why the notification could not be sent, if it could not. The application is unaffected.
   */
  notifyError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * CVs sent with job applications. Each belongs to one application and is deleted with it. They download to your computer rather than opening here, because anyone can send one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "application-files".
 */
export interface ApplicationFile {
  id: number;
  application?: (number | null) | JobApplication;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * People named as the writer of a Journal post. Add someone only after they have signed the consent form. A post with no author is shown as written by RUN APPAREL.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * For example, "Merchandiser".
   */
  role?: string | null;
  /**
   * One line.
   */
  bio?: string | null;
  photo?: (number | null) | Media;
  linkedinUrl?: string | null;
  consentRecorded?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Posts for the Journal on the website. Save a draft as often as you like: only a published post is shown, and once published its address cannot change.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts".
 */
export interface JournalPost {
  id: number;
  title: string;
  /**
   * The end of the post’s address: wear-run.com/journal/<this>. It cannot change once published.
   */
  slug: string;
  /**
   * One or two sentences. Shown in search results and link previews.
   */
  description: string;
  cluster: 'craft-and-making' | 'sialkot-stories' | 'sustainability' | 'industry-insight' | 'company-news';
  /**
   * Leave empty to show RUN APPAREL as the writer.
   */
  author?: (number | null) | Author;
  publishedAt: string;
  /**
   * Set when this was first published. From then on its address cannot change.
   */
  firstPublishedAt?: string | null;
  heroImage: number | Media;
  /**
   * The picture shown when the post is shared. At least 1200 × 630.
   */
  shareImage: number | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * At least one buyer guide and one “What we make” page.
   */
  relatedPages: (
    | '/guides/how-a-private-label-order-works'
    | '/guides/3d-garment-reference'
    | '/guides/minimum-order-and-samples'
    | '/guides/garment-printing-methods'
    | '/guides/sportswear-fabrics-and-weights'
    | '/guides/private-label-packaging'
    | '/guides/shipping-and-import-duties'
    | '/guides/cost-to-start-an-activewear-brand'
    | '/guides/pakistan-vs-china-vs-turkey'
    | '/custom-teamwear-manufacturer'
    | '/custom-activewear-manufacturer'
    | '/custom-outerwear-manufacturer'
    | '/private-label-casual-wear-manufacturer'
  )[];
  aiAssisted?: boolean | null;
  /**
   * The person who checked the post. Shown on the page.
   */
  checkedBy?: (number | null) | Author;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Stories of real orders for the website. Name the client or quote them only with their permission. Only a published case study is shown.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * The end of the address: wear-run.com/case-studies/<this>. It cannot change once published.
   */
  slug: string;
  description: string;
  /**
   * Set when this was first published. From then on its address cannot change.
   */
  firstPublishedAt?: string | null;
  /**
   * Without a name, for example "a cycling club in the UK".
   */
  clientDescription: string;
  clientNamed?: boolean | null;
  clientName?: string | null;
  whatWasMade: string;
  quantity: string;
  timeline: string;
  challenge: string;
  whatWeDid: string;
  result: string;
  clientQuote?: string | null;
  quoteAttribution?: string | null;
  clientPermission?: boolean | null;
  images?: (number | Media)[] | null;
  relatedProducts?: (number | Product)[] | null;
  /**
   * The picture shown when the case study is shared. At least 1200 × 630.
   */
  shareImage: number | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * One line per person, per document, per day (Pakistan time). Counts of people are approximate. WhatsApp visits usually show as Safari or Chrome. Email scanners such as Outlook Safe Links can look like a person. Lines older than 12 months are deleted automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-visits".
 */
export interface DocumentVisit {
  id: number;
  day: string;
  document: 'catalogue' | 'profile';
  kind: 'person' | 'private' | 'link-preview' | 'robot' | 'old-link';
  visitor?: string | null;
  firstAt?: string | null;
  lastAt?: string | null;
  minutesActive?: number | null;
  opens?: number | null;
  furthestPage?: number | null;
  pagesTotal?: number | null;
  downloads?: number | null;
  country?: string | null;
  region?: string | null;
  city?: string | null;
  timezone?: string | null;
  network?: string | null;
  device?: string | null;
  system?: string | null;
  browser?: string | null;
  language?: string | null;
  cameFrom?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-visit-salts".
 */
export interface DocumentVisitSalt {
  id: number;
  day: string;
  salt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-visit-emails".
 */
export interface DocumentVisitEmail {
  id: number;
  week: string;
  status: 'sent' | 'failed';
  sentAt?: string | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'raw-uploads';
        value: number | RawUpload;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'inquiry-files';
        value: number | InquiryFile;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: number | JobApplication;
      } | null)
    | ({
        relationTo: 'application-files';
        value: number | ApplicationFile;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'journal-posts';
        value: number | JournalPost;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'document-visits';
        value: number | DocumentVisit;
      } | null)
    | ({
        relationTo: 'document-visit-salts';
        value: number | DocumentVisitSalt;
      } | null)
    | ({
        relationTo: 'document-visit-emails';
        value: number | DocumentVisitEmail;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  hasAPIKey?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sourceReference?: T;
  sizeWarning?: T;
  artworkVerdict?: T;
  artworkOverrideReason?: T;
  _objectKey?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "raw-uploads_select".
 */
export interface RawUploadsSelect<T extends boolean = true> {
  targetProduct?: T;
  detail?: T;
  status?: T;
  retry?: T;
  resultGlb?: T;
  report?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  status?: T;
  sortOrder?: T;
  productName?: T;
  garmentType?: T;
  shortDescription?: T;
  productCode?: T;
  slug?: T;
  category?: T;
  colourways?: T | ProductColourwaySelect<T>;
  modelComingSoon?: T;
  rawUploads?: T;
  variantMode?: T;
  glbAsset?: T;
  posterFallback?: T;
  variantsVerified?: T;
  fileColours?: T;
  fileColourDetails?: T;
  fabricComposition?: T;
  gsm?: T;
  garmentFit?: T;
  performanceFeatures?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  customisationIntro?: T;
  customisationSteps?:
    | T
    | {
        number?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  frontCameraOrbit?: T;
  backCameraOrbit?: T;
  sideCameraOrbit?: T;
  cameraTarget?: T;
  defaultFieldOfView?: T;
  catalogueUrl?: T;
  retiredMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductColourway_select".
 */
export interface ProductColourwaySelect<T extends boolean = true> {
  displayName?: T;
  slug?: T;
  variantId?: T;
  posterPreview?: T;
  renderImage?: T;
  renderScreen?: T;
  altText?: T;
  hexSwatch?: T;
  glbAsset?: T;
  active?: T;
  note?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  type?: T;
  event?: T;
  product?: T;
  variant?: T;
  placement?: T;
  message?: T;
  ua?: T;
  lcpMs?: T;
  cls?: T;
  inpMs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  email?: T;
  message?: T;
  jobTitle?: T;
  country?: T;
  phone?: T;
  subject?: T;
  files?: T;
  filesError?: T;
  status?: T;
  notified?: T;
  notifyError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiry-files_select".
 */
export interface InquiryFilesSelect<T extends boolean = true> {
  inquiry?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  role?: T;
  years?: T;
  note?: T;
  files?: T;
  filesError?: T;
  status?: T;
  deleteAfter?: T;
  notified?: T;
  notifyError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "application-files_select".
 */
export interface ApplicationFilesSelect<T extends boolean = true> {
  application?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  linkedinUrl?: T;
  consentRecorded?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts_select".
 */
export interface JournalPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  cluster?: T;
  author?: T;
  publishedAt?: T;
  firstPublishedAt?: T;
  heroImage?: T;
  shareImage?: T;
  body?: T;
  relatedPages?: T;
  aiAssisted?: T;
  checkedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  firstPublishedAt?: T;
  clientDescription?: T;
  clientNamed?: T;
  clientName?: T;
  whatWasMade?: T;
  quantity?: T;
  timeline?: T;
  challenge?: T;
  whatWeDid?: T;
  result?: T;
  clientQuote?: T;
  quoteAttribution?: T;
  clientPermission?: T;
  images?: T;
  relatedProducts?: T;
  shareImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-visits_select".
 */
export interface DocumentVisitsSelect<T extends boolean = true> {
  day?: T;
  document?: T;
  kind?: T;
  visitor?: T;
  firstAt?: T;
  lastAt?: T;
  minutesActive?: T;
  opens?: T;
  furthestPage?: T;
  pagesTotal?: T;
  downloads?: T;
  country?: T;
  region?: T;
  city?: T;
  timezone?: T;
  network?: T;
  device?: T;
  system?: T;
  browser?: T;
  language?: T;
  cameFrom?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-visit-salts_select".
 */
export interface DocumentVisitSaltsSelect<T extends boolean = true> {
  day?: T;
  salt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-visit-emails_select".
 */
export interface DocumentVisitEmailsSelect<T extends boolean = true> {
  week?: T;
  status?: T;
  sentAt?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  email: string;
  /**
   * International format; the viewer builds wa.me links from the digits.
   */
  whatsappNumber: string;
  /**
   * Kept on record only. The website has had no “Catalogue” button since 4 September 2026 — these product pages are indexed by Google and the catalogue is a 54 MB trade PDF. Changing this does not change anything a visitor sees.
   */
  catalogueUrl: string;
  /**
   * The little picture on the browser tab. Leave this empty and the built-in RUN mark is used. A SQUARE picture works best — a wide logo gets squashed into a tiny square and becomes unreadable. Around 512 x 512 is plenty. Upload it under Photos & 3D files first, then pick it here.
   */
  logo?: (number | null) | Media;
  /**
   * The brand name in the top bar. Short is better: on the narrowest phones only about 12 characters fit, and a longer name is shortened with "…" there. The page layout is safe either way.
   */
  temporaryWordmark: string;
  footerLine: string;
  legalLine: string;
  /**
   * The green tab at the top of the footer. Links to the Contact page.
   */
  ctaLabel: string;
  /**
   * The big question. The LAST word is set in italic green automatically.
   */
  ctaQuestion: string;
  ctaSubline: string;
  /**
   * Drawn as a measurement line under the question. This is a promise in writing.
   */
  ctaPromise: string;
  /**
   * Facts a buyer wants before they write to you. Every box is optional and the footer hides what is blank. The clock light ("Open now") is worked out from the hours — leave them blank and no light is shown.
   */
  capacity?: {
    /**
     * e.g. "50 pcs per style"
     */
    moq?: string | null;
    /**
     * e.g. "4–6 weeks from approval"
     */
    leadTime?: string | null;
    hoursFirstDay?: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun') | null;
    hoursLastDay?: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun') | null;
    /**
     * HH:MM, Sialkot time
     */
    hoursOpen?: string | null;
    /**
     * HH:MM, Sialkot time
     */
    hoursClose?: string | null;
  };
  /**
   * Optional, shown under the address. e.g. "32.49° N · 74.52° E". Only if you know it is right.
   */
  worksCoordinates?: string | null;
  /**
   * Only standards you actually hold. Each one is a claim buyers may ask you to prove.
   */
  certifications?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Reference copy of the enquiry template the viewer generates for email/WhatsApp. Tokens: [Product Name], [Product Code], [Colour].
   */
  inquiryTemplate?: {
    subject?: string | null;
    bodyIntro?: string | null;
    microcopy?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The settings every NEW garment starts with. Changing something here changes what the NEXT product you create begins with — it does NOT rewrite any product you have already made, even one made a minute ago. To fix one existing product, open it and edit it directly. (“How we build your product” does not work this way and is not here — it is one text for every product, in its own screen under Content.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogue-defaults".
 */
export interface CatalogueDefault {
  id: number;
  /**
   * The value a NEW product starts with. Kept on record only. The website has had no “Catalogue” button since 4 September 2026 — these product pages are indexed by Google and the catalogue is a 54 MB trade PDF. Changing this does not change anything a visitor sees.
   */
  catalogueUrl: string;
  /**
   * Shown on a NEW product when someone scans a QR code for a colour that has been switched off.
   */
  retiredMessage: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Retired. Customisation copy is written per garment, on each product’s own “How we build your product” tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "build-process".
 */
export interface BuildProcess {
  id: number;
  /**
   * The paragraph above the steps, on every product page. Business-to-business wording only — this is not a shop.
   */
  customisationIntro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown in order as the “How we build your product” list on every product page. Deleting every step removes the list from every page.
   */
  customisationSteps?:
    | {
        number: number;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  email?: T;
  whatsappNumber?: T;
  catalogueUrl?: T;
  logo?: T;
  temporaryWordmark?: T;
  footerLine?: T;
  legalLine?: T;
  ctaLabel?: T;
  ctaQuestion?: T;
  ctaSubline?: T;
  ctaPromise?: T;
  capacity?:
    | T
    | {
        moq?: T;
        leadTime?: T;
        hoursFirstDay?: T;
        hoursLastDay?: T;
        hoursOpen?: T;
        hoursClose?: T;
      };
  worksCoordinates?: T;
  certifications?:
    | T
    | {
        name?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  inquiryTemplate?:
    | T
    | {
        subject?: T;
        bodyIntro?: T;
        microcopy?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogue-defaults_select".
 */
export interface CatalogueDefaultsSelect<T extends boolean = true> {
  catalogueUrl?: T;
  retiredMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "build-process_select".
 */
export interface BuildProcessSelect<T extends boolean = true> {
  customisationIntro?: T;
  customisationSteps?:
    | T
    | {
        number?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}