import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import {
  BACKDROP_FILTER_ALLOW_LIST,
  COLOURED_EDGE_ALLOW_LIST,
  extractLeafRules,
  findBackdropFilters,
  findColouredEdges,
  findForbiddenDependencies,
  findHeadlineBadges,
  findIconBoxRows,
  findUiKitFingerprints,
} from '../../../scripts/vibecoded-rules.mjs'

/**
 * VC-07, VC-08, VC-10, VC-11, VC-12, VC-13 — the rules themselves, each fed a planted case it
 * must report AND a clean one it must pass, before any "0 found" from the browser specs
 * (apps/cms/e2e/vibecoded.spec.ts, apps/viewer/e2e/vibecoded.spec.ts) is trusted.
 */

const REPO = join(import.meta.dirname, '..', '..', '..')

describe('each rule reports a planted case and passes a clean one', () => {
  it('VC-07: a thick one-sided coloured stripe, not a hairline or a four-sided border', () => {
    const rules = extractLeafRules(`
      .card { border-left: 4px solid var(--volt); }
      .aside { border-inline-start-color: #7c3aed; }
      .hairline { border-left: 1px solid var(--dimension); }
      .icon-bar { border-block-start: 2px solid; }
      .quiet { border-inline-start: 3px solid var(--line); }
      .btn { border: 2px solid var(--volt); }
    `)
    expect(findColouredEdges(rules).map((r) => r.selector)).toEqual(['.card', '.aside'])
  })

  it('VC-07: the allow-list covers only the exact selectors it names', () => {
    const rules = extractLeafRules(`
      .form-notice--ok { border-inline-start-color: var(--dimension); }
      .form-notice--ok, .promo { border-inline-start-color: var(--volt); }
    `)
    expect(findColouredEdges(rules).map((r) => r.selector)).toEqual(['.form-notice--ok, .promo'])
  })

  it('VC-08: any backdrop-filter, prefixed or not, inside @media or not', () => {
    const rules = extractLeafRules(`
      @media (min-width: 1px) { .panel { -webkit-backdrop-filter: blur(12px); } }
      .glass { backdrop-filter: saturate(180%) blur(20px); }
      .off { backdrop-filter: none; }
      @media (prefers-reduced-transparency: no-preference) { .stage__ar { backdrop-filter: blur(6px); } }
    `)
    expect(findBackdropFilters(rules).map((r) => r.selector)).toEqual(['.panel', '.glass'])
  })

  it('VC-12 / VC-13: each kit fingerprint, and not the settled @base-ui', () => {
    const found = (text: string) => findUiKitFingerprints(text).map((f) => f.kit)
    expect(found('import{X}from"lucide-react";<svg class="lucide lucide-x">')).toEqual(['Lucide'])
    expect(found('*,:before{--tw-ring-offset-width:0px}')).toEqual(['Tailwind'])
    expect(found('/*! tailwindcss v4.1.0 | MIT License */')).toEqual(['Tailwind'])
    expect(found('<div data-radix-popper-content-wrapper="">')).toEqual(['Radix'])
    expect(found('width:var(--radix-popover-trigger-width)')).toEqual(['Radix'])
    expect(found('// generated by shadcn')).toEqual(['shadcn'])
    expect(found('import"@base-ui-components/react/dialog";data-base-ui-inert')).toEqual([])
    expect(found('Lucid prose about a lucent fabric, with wind and tailored cuts.')).toEqual([])
  })

  it('VC-12 / VC-13: a manifest naming a kit, in any dependency field', () => {
    expect(
      findForbiddenDependencies({
        dependencies: { 'lucide-react': '1', react: '19' },
        devDependencies: { tailwindcss: '4', '@tailwindcss/vite': '4' },
        peerDependencies: { '@radix-ui/react-dialog': '1' },
        optionalDependencies: { 'tailwind-merge': '3' },
      }),
    ).toEqual([
      'lucide-react',
      'tailwindcss',
      '@tailwindcss/vite',
      '@radix-ui/react-dialog',
      'tailwind-merge',
    ])
    expect(
      findForbiddenDependencies({ dependencies: { '@base-ui/react': '1', lenis: '1' } }),
    ).toEqual([])
  })

  it('VC-10: three or more siblings that each carry an icon and a heading', () => {
    expect(
      findIconBoxRows([
        { parent: 'features', children: 3, withIconAndHeading: 3 },
        { parent: 'cards', children: 5, withIconAndHeading: 2 },
        { parent: 'pair', children: 2, withIconAndHeading: 2 },
      ]).map((g) => g.parent),
    ).toEqual(['features'])
  })

  it('VC-11: a painted pill right before the headline, not a bare label', () => {
    expect(
      findHeadlineBadges([
        { where: 'pill', height: 28, radius: 999, hasBackground: true, hasBorder: false },
        { where: 'outlined pill', height: 28, radius: 14, hasBackground: false, hasBorder: true },
        { where: 'mono label', height: 18, radius: 0, hasBackground: false, hasBorder: false },
        {
          where: 'unpainted round',
          height: 28,
          radius: 999,
          hasBackground: false,
          hasBorder: false,
        },
        { where: 'soft box', height: 40, radius: 6, hasBackground: true, hasBorder: true },
      ]).map((b) => b.where),
    ).toEqual(['pill', 'outlined pill'])
  })
})

describe('the repository today', () => {
  // Every stylesheet the two apps ship, read by FOLDER so a new file is covered without an
  // edit here: a hand-written list missed packages/ui/src/notch.css on the first run.
  const cssFiles = [
    'apps/cms/src/app/(frontend)',
    'packages/ui/src',
    'apps/viewer/src/styles',
  ].flatMap((dir) =>
    readdirSync(join(REPO, dir))
      .filter((name) => name.endsWith('.css'))
      .map((name) => `${dir}/${name}`),
  )
  expect(cssFiles.length, 'no stylesheet was found, so nothing was checked').toBeGreaterThanOrEqual(
    5,
  )
  const rules = cssFiles.flatMap((file) => extractLeafRules(readFileSync(join(REPO, file), 'utf8')))

  it('VC-07 / VC-08: the source CSS carries exactly the allow-listed uses, and each still exists', () => {
    expect(findColouredEdges(rules)).toEqual([])
    expect(findBackdropFilters(rules)).toEqual([])
    // A stale allow-list entry is a hole waiting for a new rule with that name.
    expect(
      findColouredEdges(rules, [])
        .map((r) => r.selector)
        .sort(),
    ).toEqual([...COLOURED_EDGE_ALLOW_LIST].sort())
    expect(findBackdropFilters(rules, []).map((r) => r.selector)).toEqual(
      BACKDROP_FILTER_ALLOW_LIST,
    )
  })

  it('VC-12 / VC-13: no workspace manifest and no lockfile entry names a UI kit', () => {
    const manifests = [
      'package.json',
      'apps/cms/package.json',
      'apps/viewer/package.json',
      'apps/shrink/package.json',
      'apps/shrink/container/package.json',
      'packages/shared/package.json',
      'packages/ui/package.json',
      'tools/asset-pipeline/package.json',
    ]
    for (const file of manifests) {
      const manifest = JSON.parse(readFileSync(join(REPO, file), 'utf8'))
      expect(findForbiddenDependencies(manifest), file).toEqual([])
    }
    for (const lock of ['pnpm-lock.yaml', 'tools/asset-pipeline/package-lock.json']) {
      expect(findUiKitFingerprints(readFileSync(join(REPO, lock), 'utf8')), lock).toEqual([])
    }
  })
})
