/**
 * Turn a garment's rendered posters into link-preview cards.
 *
 *   pnpm og:cards n001
 *
 * Reads  output/posters/<product>-<colour>-poster.webp   (the render step's output)
 * Writes apps/viewer/public/og/<product>/<colour>.jpg    (shipped in the viewer bundle)
 *        apps/viewer/worker/og-cards.ts                  (the manifest the Worker reads)
 *
 * WHY JPEG, when the posters are WebP and every browser has handled WebP for years.
 * Link crawlers are not browsers. LinkedIn documents JPG/PNG/GIF only, and iMessage
 * and WhatsApp are both unreliable with WebP — so pointing `og:image` straight at
 * media.wear-run.help's WebP poster would show a picture on Slack and X and nothing
 * at all on the two channels most likely to carry a link to a lead. The viewer
 * Worker falls back to the WebP poster when no card exists here (a correct garment
 * on some platforms beats no garment anywhere), but a card is the better answer and
 * this is how you make one.
 *
 * WHY THE PRODUCT SLUG IS AN ARGUMENT rather than parsed out of the filename:
 * `n001-wine-poster.webp` cannot be split unambiguously — product `n001` + colour
 * `wine` and product `n001-wine` + colour `` read identically, and a future
 * `n002-pro-navy-poster.webp` genuinely is ambiguous. One word from the operator
 * removes the guess. The card PATH keeps them separate for the same reason: a slug
 * can never contain `/`, so `og/<product>/<colour>.jpg` cannot collide the way a
 * hyphen-joined `og/<product>-<colour>.jpg` can.
 *
 * THE MANIFEST IS REGENERATED FROM DISK, not from what this run happened to
 * convert, so adding garment #2 cannot drop garment #1's entries. Its width and
 * height are read back out of the written JPEG rather than assumed from the source
 * — og.test.ts already exists because declared preview dimensions drifting from the
 * real file is a silent failure, and this is the same trap one level down.
 */
import { access, mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { isAbsolute, join } from 'node:path'
import sharp from 'sharp'

const REPO_ROOT = join(import.meta.dirname, '..', '..', '..')
const VIEWER_OG_DIR = join(REPO_ROOT, 'apps', 'viewer', 'public', 'og')
const MANIFEST_PATH = join(REPO_ROOT, 'apps', 'viewer', 'worker', 'og-cards.ts')

/**
 * Quality 76 rather than sharp's default 80.
 *
 * Measured on N001's five posters: the cards land at 62-75 KB each. That matters
 * because a preview card is displayed at roughly 500px wide by every client that
 * shows one, and WhatsApp in particular has historically dropped images it
 * considers heavy — so the bytes buy nothing and can cost the whole image. Kept
 * at the poster's native 1200x1500: portrait survives the letterboxing clients
 * with its caption intact, and centre-cropping clients land on the chest print.
 * Same reasoning as the og-default.jpg note in apps/viewer/index.html.
 */
const JPEG_QUALITY = 76

/** Relative paths resolve against the repo root, not the package. See CLAUDE.md. */
async function resolveDir(candidate) {
  if (isAbsolute(candidate)) return candidate
  try {
    await access(candidate)
    return candidate
  } catch {
    return join(REPO_ROOT, candidate)
  }
}

/** Every `<product>/<colour>.jpg` currently in public/og/, with its real pixel size. */
async function readManifestFromDisk() {
  const entries = {}
  let products = []
  try {
    products = await readdir(VIEWER_OG_DIR, { withFileTypes: true })
  } catch {
    return entries
  }
  for (const product of products) {
    if (!product.isDirectory()) continue
    const files = await readdir(join(VIEWER_OG_DIR, product.name))
    for (const file of files.sort()) {
      if (!file.endsWith('.jpg')) continue
      const path = join(VIEWER_OG_DIR, product.name, file)
      const { width, height } = await sharp(path).metadata()
      entries[`${product.name}/${file.replace(/\.jpg$/, '')}`] = { width, height }
    }
  }
  return entries
}

async function writeManifest(entries) {
  const keys = Object.keys(entries).sort()
  await mkdir(join(MANIFEST_PATH, '..'), { recursive: true })
  const rows = keys
    .map((key) => `  '${key}': { width: ${entries[key].width}, height: ${entries[key].height} },`)
    .join('\n')
  await writeFile(
    MANIFEST_PATH,
    `// GENERATED by tools/asset-pipeline/scripts/og-cards.mjs — do not edit by hand.
// Regenerate with:  pnpm og:cards <productSlug>
//
// Keyed '<productSlug>/<colourSlug>', matching apps/viewer/public/og/<key>.jpg.
// Width and height are read back out of each written JPEG, so a card that is
// regenerated at a different size cannot leave a stale number here. Pinned by
// apps/viewer/worker/og-cards.test.ts, which fails if this file and the directory
// ever disagree in either direction.
export interface OgCard {
  width: number
  height: number
}

export const OG_CARDS: Record<string, OgCard> = {
${rows}
}
`,
    'utf8',
  )
  return keys
}

async function main() {
  const args = process.argv.slice(2)
  // `--` is skipped deliberately: pnpm forwards the separator itself into argv, so
  // `pnpm og:cards -- n001` would otherwise take '--' as the product slug. Same
  // trap that made `eval:artwork:real -- raw/x.glb` measure the wrong file.
  const positional = args.filter((a) => !a.startsWith('--'))
  const product = positional[0]
  if (!product) {
    throw new Error(
      'Usage: pnpm og:cards <productSlug> [--posters <dir>]\n\n' +
        '  e.g. pnpm og:cards n001\n\n' +
        '  The product slug is required rather than parsed out of the poster\n' +
        '  filenames, which cannot be split into product and colour without\n' +
        '  guessing. It must match the product’s slug in the CMS exactly — that\n' +
        '  is the key the viewer Worker looks the card up by.',
    )
  }

  const postersArg = args.indexOf('--posters')
  const postersDir = await resolveDir(
    postersArg === -1 ? 'output/posters' : (args[postersArg + 1] ?? 'output/posters'),
  )

  let files
  try {
    files = (await readdir(postersDir)).filter(
      (f) => f.startsWith(`${product}-`) && f.endsWith('-poster.webp'),
    )
  } catch {
    throw new Error(`No poster directory at ${postersDir}. Render the posters first.`)
  }
  if (files.length === 0) {
    // Not a silent skip: a run that converted nothing must not read as a success,
    // or the RUNBOOK step "run pnpm og:cards" passes while shipping no cards and
    // every link for the new garment falls back to its WebP poster.
    throw new Error(
      `No posters matching ${product}-*-poster.webp in ${postersDir}.\n\n` +
        `  Found: ${(await readdir(postersDir)).join(', ') || '(nothing)'}\n\n` +
        `  Check the product slug, or pass --posters <dir>.`,
    )
  }

  await mkdir(join(VIEWER_OG_DIR, product), { recursive: true })
  for (const file of files.sort()) {
    const colour = file.slice(product.length + 1).replace(/-poster\.webp$/, '')
    const out = join(VIEWER_OG_DIR, product, `${colour}.jpg`)
    const source = await readFile(join(postersDir, file))
    // flatten() on white: a poster with an alpha channel would otherwise composite
    // onto black in JPEG, which has none. The posters are opaque today; this costs
    // nothing and stops a transparent render turning every card's backdrop black.
    const buffer = await sharp(source)
      .flatten({ background: '#ffffff' })
      .jpeg({ quality: JPEG_QUALITY, mozjpeg: true })
      .toBuffer()
    await writeFile(out, buffer)
    const { width, height } = await sharp(buffer).metadata()
    console.log(
      `  ${product}/${colour}.jpg  ${width}x${height}  ${(buffer.length / 1024).toFixed(0)} KB`,
    )
  }

  const keys = await writeManifest(await readManifestFromDisk())
  console.log(`\nManifest: apps/viewer/worker/og-cards.ts (${keys.length} card(s))`)
  console.log(keys.map((k) => `  ${k}`).join('\n'))
  console.log(
    '\nCommit both the JPEGs and the manifest. The Worker reads the manifest at\n' +
      'bundle time, so a card that is not listed there is never used.',
  )
}

main().catch((error) => {
  console.error(`\n${error.message}\n`)
  process.exit(1)
})
