import { createHash } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Generate `dist/_headers` after `vite build`. Honoured by both Cloudflare Pages
 * and Workers Static Assets. Two things are computed at build time so the policy
 * can never drift from what actually ships:
 *
 *  1. A sha256 hash of every INLINE <script> (only the theme bootstrap in
 *     index.html) → script-src allows exactly it, no 'unsafe-inline'.
 *  2. The API origin from VITE_API_BASE_URL (the same value the app was built
 *     with) → connect-src/img-src always include wherever the build calls the
 *     API, so the live viewer never breaks when that origin changes.
 *
 * The zone wildcard (https://*.wear-run.help) additionally covers media served
 * from cms/api/media.wear-run.help regardless of the API host; gstatic covers
 * model-viewer's on-demand Draco/KTX2 decoders (used only for compressed GLBs).
 */
const dir = dirname(fileURLToPath(import.meta.url))
const dist = join(dir, '..', 'dist')
const indexPath = join(dist, 'index.html')

if (!existsSync(indexPath)) {
  console.error('gen-headers: dist/index.html not found — run `vite build` first.')
  process.exit(1)
}

const html = readFileSync(indexPath, 'utf8')

// Hash inline <script> tags that have no src (module scripts carry a src and are
// covered by 'self').
const inlineHashes = []
for (const match of html.matchAll(/<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/gi)) {
  const body = match[1]
  if (!body) continue
  inlineHashes.push(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`)
}

const apiOrigin = (() => {
  try {
    return new URL(process.env.VITE_API_BASE_URL || 'https://cms.wear-run.help').origin
  } catch {
    return 'https://cms.wear-run.help'
  }
})()

const CF_SCRIPT = 'https://static.cloudflareinsights.com'
const CF_CONNECT = 'https://cloudflareinsights.com https://static.cloudflareinsights.com'
const GSTATIC = 'https://www.gstatic.com'
const ZONE = 'https://*.wear-run.help'

const csp = [
  `default-src 'self'`,
  `base-uri 'self'`,
  `object-src 'none'`,
  `frame-ancestors 'none'`,
  `form-action 'none'`,
  // 'wasm-unsafe-eval' — model-viewer's Draco/KTX2 wasm decoders; no eval.
  `script-src 'self' 'wasm-unsafe-eval' ${inlineHashes.join(' ')} ${CF_SCRIPT}`.replace(/\s+/g, ' '),
  // 'unsafe-inline' for styles only — the motion layer animates via style
  // attributes and model-viewer injects styles into its shadow DOM. Style
  // injection is far lower risk than script injection (which stays hash-locked).
  `style-src 'self' 'unsafe-inline'`,
  `img-src 'self' data: blob: ${apiOrigin} ${ZONE}`,
  `font-src 'self'`,
  `connect-src 'self' ${apiOrigin} ${ZONE} ${GSTATIC} ${CF_CONNECT}`,
  `worker-src 'self' blob:`,
  `manifest-src 'self'`,
  `upgrade-insecure-requests`,
].join('; ')

const contents = `# GENERATED by scripts/gen-headers.mjs — do not edit by hand.
# CSP origins are baked in from VITE_API_BASE_URL at build time. Honoured by
# Cloudflare Pages and by Workers Static Assets.

# Hashed build assets are immutable
/assets/*
  Cache-Control: public, max-age=31536000, immutable

# The SPA shell must always revalidate so new deploys go live immediately
/index.html
  Cache-Control: public, max-age=0, must-revalidate

/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Content-Security-Policy: ${csp}
`

writeFileSync(join(dist, '_headers'), contents)
console.log(
  `gen-headers: wrote dist/_headers (api origin ${apiOrigin}, ${inlineHashes.length} inline-script hash(es))`,
)
