import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildCsp, inlineScriptHashes } from './csp.mjs'

/**
 * Generate `dist/_headers` after `vite build`. Honoured by both Cloudflare Pages
 * and Workers Static Assets.
 *
 * The policy itself lives in csp.mjs so it can be unit-tested — this file is only
 * the I/O around it. Everything is computed from the BUILT html and the build-time
 * env, so the policy can never drift from what actually ships.
 */
const dir = dirname(fileURLToPath(import.meta.url))
const dist = join(dir, '..', 'dist')
const indexPath = join(dist, 'index.html')

if (!existsSync(indexPath)) {
  console.error('gen-headers: dist/index.html not found — run `vite build` first.')
  process.exit(1)
}

const html = readFileSync(indexPath, 'utf8')

const csp = buildCsp({
  html,
  apiBaseUrl: process.env.VITE_API_BASE_URL,
  sentryDsn: process.env.VITE_SENTRY_DSN,
})

// Strict-Transport-Security and Permissions-Policy were both absent until
// 2026-08-03; only nosniff, Referrer-Policy and the CSP were emitted.
//
// ⚠️ `camera=()` in Permissions-Policy WILL block `<model-viewer ar>`. There is
// no AR mode today (no `ar` attribute anywhere in src/, no USDZ), so denying it
// is free — but if AR is ever added for iOS Quick Look, this is the line that
// makes it silently fail. Same for `accelerometer`/`gyroscope` if a future
// device-orientation camera control is wanted; ordinary drag-to-rotate uses
// pointer events and is unaffected.
const contents = `# GENERATED by scripts/gen-headers.mjs — do not edit by hand.
# CSP origins are baked in from VITE_API_BASE_URL at build time. Honoured by
# Cloudflare Pages and by Workers Static Assets.

# Hashed build assets are immutable
/assets/*
  Cache-Control: public, max-age=31536000, immutable

# The SPA shell must always revalidate so new deploys go live immediately
/index.html
  Cache-Control: public, max-age=0, must-revalidate

/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()
  Content-Security-Policy: ${csp}
`

writeFileSync(join(dist, '_headers'), contents)

const apiOrigin = csp.match(/connect-src [^;]*/)?.[0] ?? ''
console.log(
  `gen-headers: wrote dist/_headers (${inlineScriptHashes(html).length} inline-script hash(es))\n` +
    `  ${apiOrigin}`,
)
